# Generated by Django 3.2.7 on 2021-09-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_variation_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variation',
            managers=[
            ],
        ),
    ]
