# Generated by Django 3.2.7 on 2021-09-16 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'product gallery', 'verbose_name_plural': ' product gallery'},
        ),
    ]
