# Generated by Django 3.2.7 on 2021-09-03 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='qty',
            new_name='quantity',
        ),
    ]
